<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need) Exercises</span></div>

## Reattempt Exercise 4 (ignore)

In [52]:
import numpy as np
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  

In [53]:
numbers_array = np.array(numbers)
numbers_array

array([45, 60,  1, 30, 96,  1, 96, 57, 16,  1, 99, 62, 86, 43, 42, 60, 59,
        1,  1, 35, 83, 47, 34, 28, 68, 23, 22, 92,  1, 79,  1, 29, 94, 72,
       46, 47,  1, 74, 32, 20,  8, 37, 35,  1, 89, 29, 86, 19, 43, 61])

Using sum:

In [55]:
numbers_array <= 1

array([False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False])

In [56]:
sum(numbers_array<=1)

np.int64(9)

Using count: count only applies for lists and NOT arrays! that's why there's error

In [66]:
T_F_arrays = numbers_array <= 1
T_F_arrays

array([False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False])

In [67]:
(T_F_arrays).count(1)

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [69]:
numbers_testing_count = [45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]

number_of_ones_testing_count = numbers_testing_count.count(1)
number_of_ones_testing_count

9

Using masking

In [42]:
mask = numbers_array <= 1
numbers_array[mask]

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
len(numbers_array[mask])

9

## Reattempt Exercise 5 (ignore)

In [10]:
import numpy as np
x_1 = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
x_2 = [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

### Means of X1 and X2

In [11]:
x_1_array = np.array(x_1)
x_2_array = np.array(x_2)

x_1_mean = np.mean(x_1_array)
x_2_mean = np.mean(x_2_array)

In [12]:
x_1_mean

np.float64(38.5)

In [13]:
x_2_mean

np.float64(302.5)

### SD of X1 and X2

In [14]:
x_1_sd = np.std(x_1_array)
x_2_sd = np.std(x_2_array)

In [15]:
x_1_sd

np.float64(32.41990129534635)

In [16]:
x_2_sd

np.float64(326.0893282522444)

### Pearson Correlation

#### Calculating numerator

In [39]:
numerator_x1 = (x_1_array - x_1_mean)
numerator_x1 

array([-37.5, -34.5, -29.5, -22.5, -13.5,  -2.5,  10.5,  25.5,  42.5,
        61.5])

In [40]:
numerator_x2 = (x_2_array - x_2_mean)
numerator_x2

array([-301.5, -294.5, -275.5, -238.5, -177.5,  -86.5,   40.5,  209.5,
        426.5,  697.5])

In [44]:
sum(numerator_x1 * numerator_x2)

np.float64(104362.5)

#### Calculating denominator 

In [45]:
denominator_x1 = (x_1_array - x_1_mean)**2
sum(denominator_x1)

np.float64(10510.5)

In [46]:
denominator_x2 = (x_2_array - x_2_mean)**2
sum(denominator_x2)

np.float64(1063342.5)

In [47]:
np.sqrt(sum(denominator_x1)*sum(denominator_x2))

np.float64(105717.8383540356)

#### Calculating pearson correlation coefficient

In [48]:
104362.5 / 105717.8383540356

0.9871796626270701

In [41]:
np.corrcoef(x_1_array, x_2_array)

array([[1.        , 0.98717966],
       [0.98717966, 1.        ]])

## Exercise 1 - Total Recall

Similarity 1: List and Arrays: They can both hold lots of items

Similarity 2: List and Arrays: .append can be used for both 

Difference 1: List vs Arrays: List holds different types of items, eg string and int; but arrays only hold one type of item, eg only string or int 

Difference 2: When mathematical operations are applied to list (eg when multiplying), it grows because of concetenation. But for arrays, the math operation is applied as it is in math to every element. 

eg: mylist = [1,2,3]*2 becomes [1,2,3,1,2,3]
but myarray = array([1,2,3])*2 becomes array([2,4,6])

What is a dictionary? : It holds items like list and array, but we use { } and it is key: value. We can retrieve keys and values separately and conveniently

## Exercise 2 (Indexing)

Modify the following code to print out all elements with an odd number.

In [1]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                    # Prints 'a1'
                    # Prints 'c3'
                    # Prints 'e5'
                    # Prints 'g7'
print(py_list[8])   # Prints 'i9'

i9


In [4]:
print(py_list[0::2])

['a1', 'c3', 'e5', 'g7', 'i9']


## Exercise 3 (Index Again) 

Given the following list in Python
- Access and print the element at index 4 using forward indexing.
- Access and print the element at index 4 from the end of the list using reverse indexing.

In [5]:
elements = ['Hydrogen',
            'Helium', 'Lithium',
            'Beryllium', 'Boron', 'Carbon',
            'Nitrogen', 'Oxygen',
            'Fluorine',
            'Neon']

In [6]:
print(elements[4])

Boron


In [6]:
print(elements[-4])

Nitrogen


## Exercise 4 (How many ones)

Use the concepts you learned in this chapter to determine the number of 1’s in the following list of numbers.

In [2]:
import numpy as np 

numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61] 

np_numbers = np.array(numbers)
number_of_ones = sum((np_numbers == 1))

In [3]:
print(f"The number of 1's here equal {number_of_ones}") 

The number of 1's here equal 9


In [4]:
# can you use .count? eg: 

numbers_testing_count = [45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]

number_of_ones_testing_count = numbers_testing_count.count(1)

print(f"The number of 1's here equal {number_of_ones_testing_count}") 

The number of 1's here equal 9


## Exercise 5 (A Matter of Statistics)

Using NumPy:

- Determine the means of x1 and x2
- Determine the standard deviations of x1 and x2 
- Determine the Pearson correlation coefficient r for the two datasets. Don’t use np.corrcoef()!
- Compare your results to np.corrcoef().

In [2]:
import numpy as np
x_1 = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
x_2 = [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [14]:
# Means of x1 and x2

mean_x_1 = np.mean(x_1)
print(f"The mean of x1 is {mean_x_1}")

mean_x_2 = np.mean(x_2)
print(f"The mean of x2 is {mean_x_2}")

The mean of x1 is 38.5
The mean of x2 is 302.5


In [15]:
# SD of x1 and x2

SD_x_1 = np.std(x_1)
print(f"The SD of x1 is {SD_x_1}")

SD_x_2 = np.std(x_2)
print(f"The SD of x2 is {SD_x_2}")

The SD of x1 is 32.41990129534635
The SD of x2 is 326.0893282522444


In [57]:
x_1_array = np.array(x_1)
# x_2_array = np.array

x_2_array = np.array(x_2)

difference_x1 = x_1_array - mean_x_1

difference_x2 = x_2_array - mean_x_2

sum_differences_num = difference_x1 * difference_x2

sum_differences.sum()

denom_x1 = (difference_x1)**2
denom_x2 = (difference_x2)**2

total_denom = denom_x1.sum() * denom_x2.sum()

total_denom.sum()**0.5 

# for sqrt, do np.sqrt

correlation_coeff = sum_differences.sum() / total_denom.sum()**0.5

print(correlation_coeff)

0.9871796626270701


In [25]:
# IGNORE

# Pearson correlation coefficient r for the two datasets: 

#finding covariance first

covariance_x1x2 = np.cov(x_1, x_2)
print(covariance_x1x2) #gives you 4 values bcos it's the cov matrix
print(f"The covariance is {covariance_x1x2[0,1]}") #extract covariance value, between x1 and x2 

#finding correlation

correlation = (11595.833333333332 / (32.41990129534635*326.0893282522444)) 
print(f"The correlation is {correlation}")

[[  1167.83333333  11595.83333333]
 [ 11595.83333333 118149.16666667]]
The covariance is 11595.833333333332
The correlation is 1.0968662918078558


In [6]:
# Compare your results to np.corrcoef(). 

correlation_x1_x2 = np.corrcoef(x_1, x_2)

print(f"The correlation is {correlation_x1_x2}")

The correlation is [[1.         0.98717966]
 [0.98717966 1.        ]]
