<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1 (Total Recall)

| Term    |  Brief Description   |
| :--- | :--: | 
| Subsetting  | *to select*   |   
| Indexing  |  *selecting 1 element* |   
| Slicing   |  selecting multiple elements |   
| Masking   |  *to subset arrays*  |   

## Exercise 2  (Show me the ‘odd’ letters)

Use masking to subset the letters that correspond to the odd numbers. I.e., get the result [A, C, E, G, I].

This is a slightly tricky problem because arrays are fussy about type. So, let me give you a recipe to solve this problem.

1. Subset all the first elements.
    - You should get array(['1', '3', '2', ..., '10', '9'])
2. Convert this to integers using astype(int)
    - You must look up how astype() works.
3. Use % to get the remainder for division by 2.
    - You should get array([1, 1, 0, ..., 0, 1]).
4. Use the previous result to create a mask that checks if the remainder is zero or not
    - You should get array([True, True, False, ..., False, True]).
    - Now you have identified the locations of the odd numbers.
5. Use the mask and extract the corresponding second elements.

In [2]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [5]:
# Subset all first elements
np.array(np_array_2d[0::,0])

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [14]:
x = np.array(np_array_2d[0::,0]).astype(int)

np.array(np_array_2d[0::,0]).astype(int)

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [16]:
# Use % to get the remainder for division by 2.

remainder = x%2

print(remainder) #i don't have the array... what's wrong? -> if you type print, then the type 'array' doesn't come up, but it is still the same thing

[1 1 0 0 1 1 0 0 0 1]


In [37]:
# create a mask that checks if the remainder is zero or not

mask = remainder > 0

print(mask)

print(type(mask))

[ True  True False False  True  True False False False  True]
<class 'numpy.ndarray'>


In [41]:
# Use the mask and extract the corresponding second elements.

#extract all 2nd elements (letters) first: 

letters = np_array_2d[0::,1]

print(letters)

# use mask to extract corres. letter

letters[mask]

['A' 'C' 'B' 'D' 'E' 'G' 'F' 'H' 'J' 'I']


array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

## Exercise 3

Consider the 2D array shown. Using your knowledge of NumPy masking, change:
- values below 50 to -1,
- values above 50 to +1, and
- values equal to 50 to 0.

In [22]:
import numpy as np

x = [[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

In [23]:
# changing value below 50 to -1 

below_50 = x < 50 # list and integer comparison isn't allowed, so nd to make into array

TypeError: '<' not supported between instances of 'list' and 'int'

In [30]:
# changing value below 50 to -1 
x_array = np.array(x)
x_array[x_array < 50] = -1
x_array[x_array > 50] = +1
x_array[x_array == 50] = 0
print(x_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
