<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

In [49]:
import numpy as np
ran_no=np.random.randint(0,100,100)

In [50]:
mask = (ran_no < 50) & (ran_no%2==1) #Masking

In [51]:
ran_no[mask] #it retrieves all numbers that are < 50 and odd 

array([ 3,  1,  1,  9, 41, 29,  7, 17, 25, 15,  5,  3, 25,  9, 39, 25, 37,
       35, 39, 25, 15, 39, 31, 43, 49,  7, 15, 49])

In [55]:
ran_no[mask][5] #python has 0 indexing, you are indexing here to get subset of values 
 #negative indexing applies for both array and list 

np.int64(29)

In [56]:
ran_no[mask][-2] #negative indexing applies for both array and list 

np.int64(15)

#### lists - u can have multiple types (can be int and string)
#### array - only allow for 1 type (so both string, or both int)

In [5]:
import numpy as np
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [6]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

In [7]:
np_array_2d

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U21')

### Indexing concept applies for both array & list - but sometimes we have list within list, how does it work?

In [10]:
#many lists within a list, but you can do this with numpy array
py_list_2d[0]

[1, 'A']

In [12]:
np_array_2d[0,1] # do 0 first (you get[1, 'A'], then take the first: you get 'A')

np.str_('A')

## 1.3 Accessing data from a dictionary

In [13]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

superhero_info = {
    "Natasha Romanoff": ["Black Widow", "Joannsson"],
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

#key: value. value can be anything from list, array or dictionary

In [14]:
superhero_info['Natasha Romanoff']

['Black Widow', 'Joannsson']

In [15]:
superhero_info['Natasha Romanoff'][1]

'Joannsson'

## 1.4 Higher dimensional lists

# 2 Lists vs. Arrays

In [3]:
py_list = [1,2,3,4,5]

py_list

[1, 2, 3, 4, 5]

In [4]:
import numpy as np
np_array = np.array([1,2,3,4,5])
np_array

array([1, 2, 3, 4, 5])

They both store the same information, but fundamentally have different capabilities 

Lists - to grow data and simulation

Array - mathematics and science... 

You can first make it as a list (because you want to edit and grow it etc..) but when nd to do calc, convert into array. See below:

In [6]:
py_list1 = [3,6,9,12]*3
py_list1

[3, 6, 9, 12, 3, 6, 9, 12, 3, 6, 9, 12]

In [9]:
np_py_list1 = np.array(py_list1)

np_py_list1 

array([ 3,  6,  9, 12,  3,  6,  9, 12,  3,  6,  9, 12])

### Things you can do or not

In [ ]:
py_list = [1,2,3,4,5]
np_array = np.array([1,2,3,4,5])

### Difference between list and array when doing the same operations

#### Adding them tgt 

In [10]:
py_list + 1

TypeError: can only concatenate list (not "int") to list

In [12]:
py_list + [1]

[1, 2, 3, 4, 5, 1]

In [11]:
np_array + 1

array([2, 3, 4, 5, 6])

#### Multiplying them tgt

In [13]:
py_list * 3       #growing your list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [16]:
np_array * 3     #multiply each element by 3     

array([ 3,  6,  9, 12, 15])

## 2.1 Size

In [17]:
len(np_array)

5

In [18]:
np_array.size

5

In [20]:
np_array.shape # if numpy array has multiple functions

(5,)

## 2.2 Arrays are fussy about type

## 2.7 Asking questions in Numpy & List

In [21]:
'a' in ['a', 'b', 'c']

True

In [23]:
my_random_number = np.random.randint(0,100,10)          # start from 0, end at 100, size=10 (make 10 numbers)
my_random_number

array([63, 49, 30, 97, 17, 62, 64, 36, 23, 61])

In [24]:
my_random_number <50

array([False,  True,  True, False,  True, False, False,  True,  True,
       False])

What happened? 

It posed questions to all elements, asking if each element <50? if <50, true.. if >50, false

### Masking 

In [31]:
mask = my_random_number <50

In [32]:
my_random_number[mask]

array([49, 30, 17, 36, 23])

What does masking do? What happened above?

It gives you ALL the elements < 50 directly, removing all True False 

In [33]:
mask2 = (my_random_number <50) & (my_random_number % 2 >0)

In [35]:
my_random_number[mask2]

array([49, 17, 23])

What happened here? 

I generated both <50 AND odd no.

In [37]:
mask3 = (my_random_number <50) | (my_random_number % 2 >0)

In [38]:
my_random_number[mask3] ## vertical line is 'or'

array([63, 49, 30, 97, 17, 36, 23, 61])

## 2.8 Mathematics

## Footnotes