<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Hello, Jupyter! (Need)</span></div>

# 1 Jupyter, who?

# 2 Anaconda & Miniconda

## 2.1 Download & install Miniconda

# 3 Hello Command prompt

## 3.1 What is the command prompt

## 3.2 Opening the prompt

## 3.3 Navigate using the prompt

## 3.4 Using the prompt with conda

# 4 Installing Jupyter and other stuff

## 4.1 Jupyter… the first run

## Footnotes

In [4]:
type(6.6)

float

In [8]:
x = 1
print(x, type(x))
x=float(x), print(x, type(x))

1 <class 'int'>
1 <class 'int'>


In [10]:
test = [[1,2], [3,4],[5,6],[7,8]]

test[0][1]

2

In [13]:
import numpy as np
test_array = np.array(test)
test_array[0,1]

np.int64(2)

In [3]:
x = [45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]

no_of_59 = x.count(59)

print(no_of_59)

1


In [20]:
points = [1, 4, 2, 9, 7, 8, 9, 3, 1]

x = points.count(9)

In [6]:
import numpy as np 

numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61] 

np_numbers = np.array(numbers)
number_of_59 = sum((np_numbers == 59))

print(number_of_59)

1


In [16]:
import numpy as np 

numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61] 

np_numbers = np.array(numbers)

my_mask =np_numbers <= 1 # Asking a question, and answer is True or False only

In [10]:
np_numbers[my_mask]    # Shows me answers that are only True 

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
(np_numbers[my_mask]).shape   # Giving me the number of 1s that appear 

len(np_numbers[my_mask])

9

In [20]:
import numpy as np
x = np.array([1,2,3,4])
x.astype(str)

array(['1', '2', '3', '4'], dtype='<U21')

In [21]:
y = np.array(['1','2','3','4'])
y.astype(int)

array([1, 2, 3, 4])

In [22]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [27]:
x = np_array_2d[:,0]
x

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [31]:
x_int= x.astype(int)
x_int

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [35]:
remainder = x_int % 2
remainder 

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [38]:
my_mask = remainder > 0 # Asking question if true or false, returns both
my_mask 

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [42]:
super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [43]:
for count, name in enumerate(real_names):
    print(f'{count}: {name} is a Marvel superhero!') # Gives number (stored in count) & your superhero

0: Natasha Romanoff is a Marvel superhero!
1: Tony Stark is a Marvel superhero!
2: Stephen Strange is a Marvel superhero!


In [46]:
for index, name in enumerate(real_names, 100):
    superhero_name = super_names[index]
    print(f'{name} is {superhero_name}!')

IndexError: list index out of range

In [65]:
import numpy as np

for i in range(10): 
    x = np.random.rand(10)
    mask = x >= 0.5
    x[mask]
    len(x[mask])
    print(f'experiment: {i+1} no. of heads = {len(x[mask])}')
 

experiment: 1 no. of heads = 5
experiment: 2 no. of heads = 7
experiment: 3 no. of heads = 3
experiment: 4 no. of heads = 3
experiment: 5 no. of heads = 7
experiment: 6 no. of heads = 4
experiment: 7 no. of heads = 4
experiment: 8 no. of heads = 4
experiment: 9 no. of heads = 7
experiment: 10 no. of heads = 3


In [55]:
y = np.random.rand(10)
mask = y >= 0.5
mask
y[mask]
len(y[mask])

4